#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'geo_types_types'


class User
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  USERNAME = 2

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    USERNAME => {:type => ::Thrift::Types::STRING, :name => 'username', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field id is unset!') unless @id
  end

  ::Thrift::Struct.generate_accessors self
end

class Checkin
  include ::Thrift::Struct, ::Thrift::Struct_Union
  USER = 1
  TIMESTAMP = 2

  FIELDS = {
    USER => {:type => ::Thrift::Types::STRUCT, :name => 'user', :class => ::User},
    TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field user is unset!') unless @user
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field timestamp is unset!') unless @timestamp
  end

  ::Thrift::Struct.generate_accessors self
end

